[package]
name = "tiny-ini"
version = "0.1.0"
authors = ["Alexey Golubev <dr.freecx@gmail.com>", "Vova Abdrakhmanov <369565@gmail.com>"]

[lib]
name = "tiny_ini"

[[example]]
name = "test"

[dependencies]
